MODULE aiousb
DESCRIPTION IDL interface to ACCES I/O usb modules
VERSION 0.1
SOURCE David G. Grier, New York University
BUILD_DATE MAR 27 2015
FUNCTION  AIOUSB_INIT 0 0
PROCEDURE AIOUSB_EXIT 0 0
FUNCTION  AIOUSB_GETDEVICEPROPERTIES 1 1
FUNCTION  AIOUSB_COMMTIMEOUT 1 2
PROCEDURE AIOUSB_SETDACRANGE 2 2
